# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_unread',
        ),
        migrations.AddField(
            model_name='notification',
            name='unread_subscribers_ids',
            field=models.TextField(default='', help_text="comma sepereted integer, id's of unread subscribers"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subscribers_ids',
            field=models.TextField(default='', help_text="comma sepereted integer, subscribers id's"),
        ),
    ]
