# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_is_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subscribers_ids',
            field=models.TextField(default='', help_text="comma sepereted integer, read notification id's"),
        ),
    ]
