# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_subscribers_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
