# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20171024_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subscribers_ids',
            field=models.TextField(default='', help_text="comma sepereted integer, read subscribers id's"),
        ),
    ]
