# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_mark_as_read_notifications_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mark_as_read_notifications_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='read_notifications_id',
            field=models.TextField(default='0', help_text="comma sepereted integer, read notification id's"),
        ),
    ]
