# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171022_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='read_notifications_id',
        ),
    ]
