# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subscribers',
            field=models.ManyToManyField(related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
