# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20171022_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
