# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['accepted', 'upvote', '-created']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='is_banned',
            new_name='accepted',
        ),
    ]
